### ISSUE TITLE
Errors with no response body during `put` print as empty error messages

### ISSUE THREAD

**Issue by NHDaly** [JuliaServices/CloudStore.jl#25]
We were getting these empty error logs in datadog:
```julia
@ CloudStore.API ~/.julia/packages/CloudStore/SbQX7/src/put.jl:58
```
It seems they're coming from here:
https://github.com/JuliaServices/CloudStore.jl/blob/16608f972623ac8a3a49089d094ac8e4654199ee/src/put.jl#L57-L59

But i also see that line is removed from `main`. Is this already addressed? What do these errors mean? Should they be handled by the calling code?

**Comment by quinnj** [comment]
Yes, these errors should be handled by calling code; the `@error` log was just there during a debug session where I was also passing `status_exception=false` to see response errors; in normal code, this should mostly be invisible, but in the Azure case, when you do a PUT, they return a _201_ response status, so we hit this code path, but the response body is _emtpy_, so there's nothing to log.
